### ISSUE TITLE
urxvt字体间距太大

### ISSUE THREAD

**Issue by triomino** [TsReaper/arch-config#1]
配完后终端字体是这样的：
![image](https://user-images.githubusercontent.com/15924998/41759742-8fcc272c-7622-11e8-91e4-b896172b93f7.png)
但是在idea里打开终端，字体间距很小
![image](https://user-images.githubusercontent.com/15924998/41759803-d13f6d68-7622-11e8-8bf7-e95ad6439e1f.png)

感觉后者更舒服啊。。学长知道怎么办吗。

**Comment by triomino** [comment]
用了letterSpace -2 感觉每个字还是有点肥。凑合能看

**Comment by TsReaper** [comment]
学长没有安装科学的字体... 我博客里写了使用的字体，学长可以看看：

https://www.cnblogs.com/tsreaper/p/arch-config.html
